name: Build and test
on:
  pull_request:
    branches: ["main"]

concurrency:
  group: code-check-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Read node and npm versions from package.json
        uses: skjnldsv/read-package-engines-version-actions@v3
        id: package-engines-versions

      - name: Setup node
        uses: actions/setup-node@v5
        with:
          node-version: ${{ steps.package-engines-versions.outputs.nodeVersion }}

      - name: Install Dependencies
        run: npm ci

      - name: Tests
        run: npm run ci-test

      - name: Formatting
        run: npm run prettier:check

      - name: Lint
        run: npm run lint
